(async function(){
  const api=async(u,o={})=>{const headers={...(o.headers||{})};const token=sessionStorage.getItem('dayflowSessionToken');if(token)headers['X-Session-Token']=token;const r=await fetch(u,{...o,headers,credentials:'include'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d};
  const notifications=document.getElementById('notificationsData');
  if(notifications){try{const d=await api('/api/notifications');notifications.innerHTML=d.notifications.length?d.notifications.map(n=>`<div class="data-row"><span><b>${n.title}</b><br>${n.message}</span><span>${n.is_read?'Read':'New'}</span></div>`).join(''):'<p>No notifications.</p>'}catch(e){notifications.innerHTML=`<p style="color:#b91c1c">${e.message}</p>`}}
  const corrections=document.getElementById('correctionsData');
  if(corrections){try{const d=await api('/api/attendance/corrections');corrections.innerHTML=d.corrections.length?d.corrections.map(c=>`<div class="data-row"><span>${c.employee_name} · ${c.reason}</span><span>${c.status}</span></div>`).join(''):'<p>No pending corrections.</p>'}catch(e){corrections.innerHTML=`<p style="color:#b91c1c">${e.message}</p>`}}
  const logoInput=document.getElementById('company_logo');const logoPreview=document.getElementById('companyLogoPreview');logoInput?.addEventListener('change',()=>{const file=logoInput.files?.[0];if(file&&logoPreview){const reader=new FileReader();reader.onload=()=>{logoPreview.innerHTML=`<img src="${reader.result}" alt="Selected company logo">`;};reader.readAsDataURL(file);}});
  document.querySelectorAll('form[data-endpoint]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const out=form.querySelector('.status');const button=form.querySelector('button[type="submit"]');if(button)button.disabled=true;if(out)out.textContent='Saving changes…';try{const hasFile=[...form.querySelectorAll('input[type="file"]')].some(input=>input.files?.length);const request={method:form.dataset.method||'POST'};if(hasFile||form.enctype==='multipart/form-data'){request.body=new FormData(form)}else{request.headers={'Content-Type':'application/json'};request.body=JSON.stringify(Object.fromEntries(new FormData(form)))}const d=await api(form.dataset.endpoint,request);if(out){out.style.color='#16795a';out.textContent=d.message||'Saved successfully.'}if(!hasFile)form.reset()}catch(x){if(out){out.style.color='#a52b42';out.textContent=x.message}}finally{if(button)button.disabled=false}}));
})();
